#!/usr/bin/env python3
"""Build reproducible annotation samples for Phase D."""

from __future__ import annotations

import argparse
import csv
import json
import random
from pathlib import Path
from typing import Iterable


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = "data/processed/bootstrap/discrepancies/nvd_ghsa_field_views.jsonl"
DEFAULT_OUTPUT_DIR = "data/annotations/phase_d"
DEFAULT_SEED = 20260506

SAMPLE_SPECS = (
    {
        "name": "affected_versions_fc_manual_check",
        "field": "affected_versions",
        "status": "factual_conflict",
        "size": 100,
        "purpose": "Manual false-positive check before tightening or freezing the affected_versions baseline.",
    },
    {
        "name": "severity_fc_adjudication_seed",
        "field": "severity",
        "status": "factual_conflict",
        "size": 80,
        "purpose": "Seed sample for severity factual-conflict adjudication gold construction.",
    },
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Sample field-level discrepancy rows for manual annotation."
    )
    parser.add_argument(
        "--input-path",
        default=DEFAULT_INPUT,
        help="Field view JSONL generated by build_field_discrepancies.py.",
    )
    parser.add_argument(
        "--output-dir",
        default=DEFAULT_OUTPUT_DIR,
        help="Directory for Phase D annotation samples.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=DEFAULT_SEED,
        help="Random seed used for reproducible sampling.",
    )
    parser.add_argument(
        "--preserve-existing",
        action="store_true",
        help=(
            "Refresh source values for existing sample IDs/CVEs instead of "
            "drawing a new random sample. Existing annotation fields are preserved."
        ),
    )
    return parser.parse_args()


def resolve_path(value: str) -> Path:
    path = Path(value)
    if path.is_absolute():
        return path
    return (PROJECT_ROOT / path).resolve()


def iter_jsonl(path: Path) -> Iterable[dict]:
    with path.open(encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            if not line.strip():
                continue
            row = json.loads(line)
            row["_line_number"] = line_number
            yield row


def json_cell(value) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True)


def build_annotation_row(row: dict, spec: dict, index: int) -> dict:
    field = spec["field"]
    discrepancy = row["field_discrepancies"][field]
    unified_view = row["unified_view"]
    sample_id = f"{spec['name']}:{index:03d}"
    nvd_value = discrepancy.get("nvd_value")
    ghsa_value = discrepancy.get("ghsa_value")

    return {
        "sample_id": sample_id,
        "source_line_number": row["_line_number"],
        "cve_id": row.get("cve_id"),
        "nvd_source_id": row.get("nvd_source_id"),
        "ghsa_source_id": row.get("ghsa_source_id"),
        "field": field,
        "baseline_status": discrepancy.get("status"),
        "baseline_note": discrepancy.get("note"),
        "nvd_value": nvd_value,
        "ghsa_value": ghsa_value,
        "nvd_context": {
            "severity": unified_view.get("severity", {}).get("nvd"),
            "published": unified_view.get("published", {}).get("nvd"),
            "package_names": unified_view.get("package_names", {}).get("nvd"),
            "references": unified_view.get("references", {}).get("nvd_urls"),
        },
        "ghsa_context": {
            "severity": unified_view.get("severity", {}).get("ghsa"),
            "published": unified_view.get("published", {}).get("ghsa"),
            "package_names": unified_view.get("package_names", {}).get("ghsa"),
            "references": unified_view.get("references", {}).get("ghsa_urls"),
        },
        "annotation": {
            "manual_label": "",
            "is_baseline_false_positive": "",
            "adjudicated_source": "",
            "adjudicated_value": "",
            "evidence_urls": [],
            "evidence_notes": "",
            "annotator_notes": "",
        },
    }


def write_jsonl(path: Path, rows: list[dict]) -> None:
    with path.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=False) + "\n")


def write_csv(path: Path, rows: list[dict]) -> None:
    fieldnames = [
        "sample_id",
        "source_line_number",
        "cve_id",
        "nvd_source_id",
        "ghsa_source_id",
        "field",
        "baseline_status",
        "baseline_note",
        "nvd_value_json",
        "ghsa_value_json",
        "nvd_context_json",
        "ghsa_context_json",
        "manual_label",
        "is_baseline_false_positive",
        "adjudicated_source",
        "adjudicated_value",
        "evidence_urls",
        "evidence_notes",
        "annotator_notes",
    ]
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            annotation = row["annotation"]
            writer.writerow(
                {
                    "sample_id": row["sample_id"],
                    "source_line_number": row["source_line_number"],
                    "cve_id": row["cve_id"],
                    "nvd_source_id": row["nvd_source_id"],
                    "ghsa_source_id": row["ghsa_source_id"],
                    "field": row["field"],
                    "baseline_status": row["baseline_status"],
                    "baseline_note": row["baseline_note"],
                    "nvd_value_json": json_cell(row["nvd_value"]),
                    "ghsa_value_json": json_cell(row["ghsa_value"]),
                    "nvd_context_json": json_cell(row["nvd_context"]),
                    "ghsa_context_json": json_cell(row["ghsa_context"]),
                    "manual_label": annotation["manual_label"],
                    "is_baseline_false_positive": annotation["is_baseline_false_positive"],
                    "adjudicated_source": annotation["adjudicated_source"],
                    "adjudicated_value": annotation["adjudicated_value"],
                    "evidence_urls": "",
                    "evidence_notes": annotation["evidence_notes"],
                    "annotator_notes": annotation["annotator_notes"],
                }
            )


def refresh_existing_rows(
    candidates: list[dict],
    existing_rows: list[dict],
    spec: dict,
) -> list[dict]:
    by_cve_id: dict[str, dict] = {}
    for row in candidates:
        cve_id = row.get("cve_id")
        if not cve_id:
            raise RuntimeError(f"Current {spec['name']} candidate has no cve_id")
        if cve_id in by_cve_id:
            raise RuntimeError(
                f"Current {spec['name']} candidates contain duplicate cve_id={cve_id}"
            )
        by_cve_id[cve_id] = row

    refreshed_rows = []
    seen_sample_ids: set[str] = set()
    seen_cve_ids: set[str] = set()
    for index, existing in enumerate(existing_rows, start=1):
        sample_id = existing.get("sample_id")
        cve_id = existing.get("cve_id")
        if not sample_id or sample_id in seen_sample_ids:
            raise RuntimeError(
                f"Existing {spec['name']} rows have a missing or duplicate sample_id={sample_id}"
            )
        if not cve_id or cve_id in seen_cve_ids:
            raise RuntimeError(
                f"Existing {spec['name']} rows have a missing or duplicate cve_id={cve_id}"
            )
        current = by_cve_id.get(cve_id)
        if current is None:
            raise RuntimeError(
                f"Existing {spec['name']} sample {sample_id} ({cve_id}) no longer "
                f"matches {spec['field']}={spec['status']}"
            )

        refreshed = build_annotation_row(current, spec, index)
        refreshed["sample_id"] = sample_id
        if "annotation" in existing:
            refreshed["annotation"] = existing["annotation"]
        refreshed_rows.append(refreshed)
        seen_sample_ids.add(sample_id)
        seen_cve_ids.add(cve_id)

    return refreshed_rows


def main() -> int:
    args = parse_args()
    input_path = resolve_path(args.input_path)
    output_dir = resolve_path(args.output_dir)

    if not input_path.exists():
        raise FileNotFoundError(f"Field view file not found: {input_path}")

    output_dir.mkdir(parents=True, exist_ok=True)
    rows = list(iter_jsonl(input_path))
    rng = random.Random(args.seed)
    manifest = {
        "input_path": str(input_path),
        "output_dir": str(output_dir),
        "seed": args.seed,
        "sample_selection_mode": (
            "preserve_existing" if args.preserve_existing else "random_sample"
        ),
        "samples": [],
    }

    for spec in SAMPLE_SPECS:
        candidates = [
            row
            for row in rows
            if row.get("field_discrepancies", {})
            .get(spec["field"], {})
            .get("status")
            == spec["status"]
        ]
        jsonl_path = output_dir / f"{spec['name']}.jsonl"
        csv_path = output_dir / f"{spec['name']}.csv"
        if args.preserve_existing:
            if not jsonl_path.exists():
                raise FileNotFoundError(
                    f"Cannot preserve missing existing sample: {jsonl_path}"
                )
            existing_rows = list(iter_jsonl(jsonl_path))
            for row in existing_rows:
                row.pop("_line_number", None)
            annotation_rows = refresh_existing_rows(candidates, existing_rows, spec)
        else:
            sample_size = min(spec["size"], len(candidates))
            sampled = rng.sample(candidates, sample_size)
            annotation_rows = [
                build_annotation_row(row, spec, index)
                for index, row in enumerate(sampled, start=1)
            ]

        write_jsonl(jsonl_path, annotation_rows)
        write_csv(csv_path, annotation_rows)

        manifest["samples"].append(
            {
                "name": spec["name"],
                "field": spec["field"],
                "baseline_status": spec["status"],
                "requested_size": spec["size"],
                "candidate_count": len(candidates),
                "sampled_count": len(annotation_rows),
                "preserved_existing_ids": args.preserve_existing,
                "purpose": spec["purpose"],
                "jsonl_path": str(jsonl_path),
                "csv_path": str(csv_path),
            }
        )

    manifest_path = output_dir / "sample_manifest.json"
    manifest_path.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"Annotation samples written under: {output_dir}")
    print(f"Manifest: {manifest_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
