#!/usr/bin/env python3
"""Build field-level discrepancy artifacts from aligned NVD↔GHSA pairs."""

from __future__ import annotations

import argparse
import json
import re
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable
from urllib.parse import urlsplit, urlunsplit

from packaging.version import InvalidVersion, Version


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DISCREPANCY_TYPES = (
    "equivalent",
    "representation_discrepancy",
    "incomplete",
    "temporal_discrepancy",
    "factual_conflict",
)
SEVERITY_CANONICAL_MAP = {
    "LOW": "LOW",
    "MODERATE": "MEDIUM",
    "MEDIUM": "MEDIUM",
    "HIGH": "HIGH",
    "CRITICAL": "CRITICAL",
}
SEVERITY_RANK = {"LOW": 1, "MEDIUM": 2, "HIGH": 3, "CRITICAL": 4}
REFERENCE_NORMALIZATION_PROFILES = (
    "current",
    "resource_identity_v1",
    "resource_identity_audited_v1",
)
REFERENCE_LINE_SUFFIX_RE = re.compile(r"%23L\d+(?:-L\d+)?$", re.IGNORECASE)
REFERENCE_GHSA_PATH_RE = re.compile(
    r"/(?:security/)?advisories/(GHSA-[0-9a-z-]+)$", re.IGNORECASE
)
REFERENCE_HUNTR_PATH_RE = re.compile(
    r"/bounties/([0-9a-f-]+)$", re.IGNORECASE
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build deterministic field-level discrepancy labels for matched NVD↔GHSA rows."
    )
    parser.add_argument(
        "--aligned-path",
        default="data/processed/bootstrap/aligned/nvd_ghsa_by_cve.jsonl",
        help="Aligned NVD↔GHSA JSONL path generated by build_initial_corpus.py.",
    )
    parser.add_argument(
        "--output-dir",
        default="data/processed/bootstrap/discrepancies",
        help="Directory for unified pair views and field-level discrepancy outputs.",
    )
    parser.add_argument(
        "--reference-normalization-profile",
        choices=REFERENCE_NORMALIZATION_PROFILES,
        default="current",
        help=(
            "Reference URL normalization profile. The default preserves the "
            "existing baseline; resource_identity_v1 and "
            "resource_identity_audited_v1 are experimental candidates."
        ),
    )
    return parser.parse_args()


def resolve_path(value: str) -> Path:
    path = Path(value)
    if path.is_absolute():
        return path
    return (PROJECT_ROOT / path).resolve()


def normalize_text(value: str | None) -> str | None:
    if value is None:
        return None
    stripped = value.strip()
    return stripped.lower() if stripped else None


def parse_iso_datetime(value: str | None) -> datetime | None:
    if not value:
        return None
    normalized = value.replace("Z", "+00:00")
    try:
        parsed = datetime.fromisoformat(normalized)
    except ValueError:
        return None
    if parsed.tzinfo is None:
        return parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def canonicalize_url(
    value: str | None, *, profile: str = "current"
) -> str | None:
    if not value:
        return None
    if profile not in REFERENCE_NORMALIZATION_PROFILES:
        raise ValueError(f"Unknown reference normalization profile: {profile}")
    parsed = urlsplit(value.strip())
    scheme = parsed.scheme.lower() or "https"
    netloc = parsed.netloc.lower()
    path = parsed.path.rstrip("/")
    query = parsed.query

    if profile in {"resource_identity_v1", "resource_identity_audited_v1"}:
        if scheme in {"http", "https"}:
            scheme = "https"
        if profile == "resource_identity_v1":
            path = REFERENCE_LINE_SUFFIX_RE.sub("", path)
        if (
            netloc == "liferay.dev"
            and "/known-vulnerabilities/" in path.lower()
            and "/content/cve-" in path.lower()
        ):
            query = ""
        if netloc == "github.com":
            match = REFERENCE_GHSA_PATH_RE.search(path)
            if match:
                return f"github-advisory:{match.group(1).lower()}"
        if netloc in {"huntr.com", "huntr.dev"}:
            match = REFERENCE_HUNTR_PATH_RE.fullmatch(path)
            if match:
                return f"huntr-bounty:{match.group(1).lower()}"

    if not netloc and scheme in {"http", "https"}:
        canonical = f"{scheme}:///{path.lstrip('/')}"
        if query:
            canonical = f"{canonical}?{query}"
    else:
        canonical = urlunsplit((scheme, netloc, path, query, ""))
    return canonical or None


def normalize_reference_urls(
    references: list[dict], *, profile: str = "current"
) -> list[str]:
    urls = {
        canonical
        for item in references or []
        if (canonical := canonicalize_url(item.get("url"), profile=profile))
        is not None
    }
    return sorted(urls)


def normalize_reference_hosts(references: list[dict]) -> list[str]:
    hosts = {
        item.get("host", "").lower()
        for item in references or []
        if item.get("host")
    }
    return sorted(hosts)


def normalize_cwe_ids(cwe_ids: list[str]) -> list[str]:
    values = {
        item.strip().upper()
        for item in cwe_ids or []
        if isinstance(item, str) and item.strip()
    }
    return sorted(values)


def normalize_package_names(affected: list[dict]) -> list[str]:
    values = set()
    for item in affected or []:
        for key in ("package_name", "product"):
            normalized = normalize_text(item.get(key))
            if normalized:
                values.add(normalized)
                break
    return sorted(values)


def normalize_affected_spans(affected: list[dict]) -> list[dict]:
    spans: set[tuple[str | None, ...]] = set()
    for item in affected or []:
        start_inc = item.get("version_start_including")
        start_exc = item.get("version_start_excluding")
        end_inc = item.get("version_end_including")
        end_exc = item.get("version_end_excluding")
        fixed = item.get("fixed")
        introduced = item.get("introduced")
        version = item.get("version")

        normalized_span = (
            None if start_inc in (None, "", "0") else str(start_inc),
            None if start_exc in (None, "", "0") else str(start_exc),
            None if end_inc in (None, "", "*", "-") else str(end_inc),
            None if end_exc in (None, "", "*", "-") else str(end_exc),
            None if fixed in (None, "", "*", "-") else str(fixed),
            None if introduced in (None, "", "0") else str(introduced),
            None if version in (None, "", "*", "-") else str(version),
        )
        if any(part is not None for part in normalized_span):
            spans.add(normalized_span)

    return [
        {
            "version_start_including": span[0],
            "version_start_excluding": span[1],
            "version_end_including": span[2],
            "version_end_excluding": span[3],
            "fixed": span[4],
            "introduced": span[5],
            "version": span[6],
        }
        for span in sorted(
            spans,
            key=lambda item: tuple("" if part is None else part for part in item),
        )
    ]


def effective_affected_span(span: dict) -> tuple[str | None, ...]:
    lower_including = span.get("version_start_including") or span.get("introduced")
    lower_excluding = span.get("version_start_excluding")
    upper_including = span.get("version_end_including")
    upper_excluding = span.get("version_end_excluding") or span.get("fixed")
    version = span.get("version")
    if any((lower_including, lower_excluding, upper_including, upper_excluding)):
        version = None
    return (
        lower_including,
        lower_excluding,
        upper_including,
        upper_excluding,
        version,
    )


def _major_minor_prefix(value: str | None) -> tuple[str, str] | None:
    if not value:
        return None
    parts = [part for part in value.split(".") if part]
    if len(parts) < 2:
        return None
    return (parts[0], parts[1])


def _share_major_minor_prefix(left: set[str], right: set[str]) -> bool:
    left_prefixes = {_major_minor_prefix(value) for value in left}
    right_prefixes = {_major_minor_prefix(value) for value in right}
    left_prefixes.discard(None)
    right_prefixes.discard(None)
    return bool(left_prefixes & right_prefixes)


def _any_prefix_pair(left: set[str], right: set[str]) -> bool:
    return any(
        left_value.startswith(right_value) or right_value.startswith(left_value)
        for left_value in left
        for right_value in right
    )


def _safe_parse_version(value: str | None) -> Version | None:
    if not value:
        return None
    try:
        return Version(value)
    except InvalidVersion:
        return None


def _nvd_point_span(span: dict) -> str | None:
    if any(
        span.get(key)
        for key in (
            "version_start_including",
            "version_start_excluding",
            "version_end_including",
            "version_end_excluding",
            "fixed",
            "introduced",
        )
    ):
        return None
    return span.get("version")


def _point_in_span(point: Version, span: dict) -> bool:
    lower_inc = _safe_parse_version(span.get("version_start_including") or span.get("introduced"))
    lower_exc = _safe_parse_version(span.get("version_start_excluding"))
    upper_inc = _safe_parse_version(span.get("version_end_including"))
    upper_exc = _safe_parse_version(span.get("version_end_excluding") or span.get("fixed"))
    if not any((lower_inc, lower_exc, upper_inc, upper_exc)):
        return False
    if lower_inc and point < lower_inc:
        return False
    if lower_exc and point <= lower_exc:
        return False
    if upper_inc and point > upper_inc:
        return False
    if upper_exc and point >= upper_exc:
        return False
    return True


def _all_nvd_points_within_ghsa_ranges(nvd_spans: list[dict], ghsa_spans: list[dict]) -> bool:
    nvd_points = [_safe_parse_version(_nvd_point_span(span)) for span in nvd_spans]
    if not nvd_points or any(point is None for point in nvd_points):
        return False
    return all(
        any(_point_in_span(point, ghsa_span) for ghsa_span in ghsa_spans)
        for point in nvd_points
    )


def _is_date_like_version(value: str | None) -> bool:
    return bool(value and re.match(r"^\d{4}-\d{2}-\d{2}$", value))


def compare_missing(left, right) -> dict | None:
    left_missing = left in (None, [], {})
    right_missing = right in (None, [], {})
    if left_missing and right_missing:
        return {
            "status": "equivalent",
            "note": "both sides missing",
        }
    if left_missing or right_missing:
        return {
            "status": "incomplete",
            "note": "value present on only one side",
        }
    return None


def compare_severity(nvd: dict, ghsa: dict) -> dict:
    nvd_label_raw = (nvd.get("severity") or {}).get("label")
    ghsa_label_raw = (ghsa.get("severity") or {}).get("label")
    missing = compare_missing(nvd_label_raw, ghsa_label_raw)
    if missing:
        return {
            **missing,
            "nvd_value": nvd_label_raw,
            "ghsa_value": ghsa_label_raw,
            "nvd_normalized": SEVERITY_CANONICAL_MAP.get((nvd_label_raw or "").upper()),
            "ghsa_normalized": SEVERITY_CANONICAL_MAP.get((ghsa_label_raw or "").upper()),
        }

    nvd_norm = SEVERITY_CANONICAL_MAP.get((nvd_label_raw or "").upper())
    ghsa_norm = SEVERITY_CANONICAL_MAP.get((ghsa_label_raw or "").upper())

    if nvd_norm and ghsa_norm and nvd_norm == ghsa_norm:
        status = (
            "equivalent"
            if (nvd_label_raw or "").upper() == (ghsa_label_raw or "").upper()
            else "representation_discrepancy"
        )
        note = (
            "same canonical severity label"
            if status == "representation_discrepancy"
            else "same severity label"
        )
        return {
            "status": status,
            "note": note,
            "nvd_value": nvd_label_raw,
            "ghsa_value": ghsa_label_raw,
            "nvd_normalized": nvd_norm,
            "ghsa_normalized": ghsa_norm,
        }

    if nvd_norm and ghsa_norm:
        return {
            "status": "factual_conflict",
            "note": "different canonical severity labels",
            "nvd_value": nvd_label_raw,
            "ghsa_value": ghsa_label_raw,
            "nvd_normalized": nvd_norm,
            "ghsa_normalized": ghsa_norm,
            "rank_distance": abs(SEVERITY_RANK[nvd_norm] - SEVERITY_RANK[ghsa_norm]),
        }

    return {
        "status": "representation_discrepancy",
        "note": "severity labels could not be fully canonicalized",
        "nvd_value": nvd_label_raw,
        "ghsa_value": ghsa_label_raw,
        "nvd_normalized": nvd_norm,
        "ghsa_normalized": ghsa_norm,
    }


def compare_published(nvd: dict, ghsa: dict) -> dict:
    nvd_value = nvd.get("published")
    ghsa_value = ghsa.get("published")
    missing = compare_missing(nvd_value, ghsa_value)
    if missing:
        return {
            **missing,
            "nvd_value": nvd_value,
            "ghsa_value": ghsa_value,
        }

    nvd_dt = parse_iso_datetime(nvd_value)
    ghsa_dt = parse_iso_datetime(ghsa_value)
    if nvd_dt and ghsa_dt:
        if nvd_dt == ghsa_dt:
            return {
                "status": "equivalent",
                "note": "same timestamp",
                "nvd_value": nvd_value,
                "ghsa_value": ghsa_value,
                "day_diff": 0,
            }
        if nvd_dt.date() == ghsa_dt.date():
            return {
                "status": "representation_discrepancy",
                "note": "same calendar date but different timestamp representation",
                "nvd_value": nvd_value,
                "ghsa_value": ghsa_value,
                "day_diff": 0,
            }
        return {
            "status": "temporal_discrepancy",
            "note": "different publication dates",
            "nvd_value": nvd_value,
            "ghsa_value": ghsa_value,
            "day_diff": abs((ghsa_dt.date() - nvd_dt.date()).days),
        }

    if normalize_text(nvd_value) == normalize_text(ghsa_value):
        return {
            "status": "representation_discrepancy",
            "note": "same raw timestamp after normalization",
            "nvd_value": nvd_value,
            "ghsa_value": ghsa_value,
        }

    return {
        "status": "factual_conflict",
        "note": "unparseable and unequal publication values",
        "nvd_value": nvd_value,
        "ghsa_value": ghsa_value,
    }


def compare_set_field(
    nvd_values: list[str],
    ghsa_values: list[str],
    *,
    overlap_means: str,
    conflict_note: str,
) -> dict:
    missing = compare_missing(nvd_values, ghsa_values)
    if missing:
        return {
            **missing,
            "nvd_value": nvd_values,
            "ghsa_value": ghsa_values,
        }

    nvd_set = set(nvd_values)
    ghsa_set = set(ghsa_values)
    if nvd_set == ghsa_set:
        status = "equivalent"
        note = "same canonical set"
        return {
            "status": status,
            "note": note,
            "nvd_value": sorted(nvd_set),
            "ghsa_value": sorted(ghsa_set),
        }

    if nvd_set.issubset(ghsa_set) or ghsa_set.issubset(nvd_set):
        return {
            "status": "incomplete",
            "note": "one side is a strict subset of the other",
            "nvd_value": sorted(nvd_set),
            "ghsa_value": sorted(ghsa_set),
            "shared_values": sorted(nvd_set & ghsa_set),
        }

    if nvd_set & ghsa_set:
        return {
            "status": overlap_means,
            "note": "sets overlap but differ",
            "nvd_value": sorted(nvd_set),
            "ghsa_value": sorted(ghsa_set),
            "shared_values": sorted(nvd_set & ghsa_set),
        }

    return {
        "status": "factual_conflict",
        "note": conflict_note,
        "nvd_value": sorted(nvd_set),
        "ghsa_value": sorted(ghsa_set),
    }


def compare_references(
    nvd: dict, ghsa: dict, *, normalization_profile: str = "current"
) -> dict:
    nvd_urls = normalize_reference_urls(
        nvd.get("references") or [], profile=normalization_profile
    )
    ghsa_urls = normalize_reference_urls(
        ghsa.get("references") or [], profile=normalization_profile
    )
    nvd_hosts = normalize_reference_hosts(nvd.get("references") or [])
    ghsa_hosts = normalize_reference_hosts(ghsa.get("references") or [])

    missing = compare_missing(nvd_urls, ghsa_urls)
    if missing:
        return {
            **missing,
            "nvd_value": nvd_urls,
            "ghsa_value": ghsa_urls,
            "nvd_hosts": nvd_hosts,
            "ghsa_hosts": ghsa_hosts,
        }

    nvd_set = set(nvd_urls)
    ghsa_set = set(ghsa_urls)
    if nvd_set == ghsa_set:
        raw_nvd_count = len(nvd.get("references") or [])
        raw_ghsa_count = len(ghsa.get("references") or [])
        status = (
            "representation_discrepancy"
            if raw_nvd_count != len(nvd_set) or raw_ghsa_count != len(ghsa_set)
            else "equivalent"
        )
        note = (
            "same canonical reference URLs after deduplication"
            if status == "representation_discrepancy"
            else "same canonical reference URLs"
        )
        return {
            "status": status,
            "note": note,
            "nvd_value": sorted(nvd_set),
            "ghsa_value": sorted(ghsa_set),
            "nvd_hosts": nvd_hosts,
            "ghsa_hosts": ghsa_hosts,
        }

    if nvd_set.issubset(ghsa_set) or ghsa_set.issubset(nvd_set):
        return {
            "status": "incomplete",
            "note": "one side lists a strict subset of canonical references",
            "nvd_value": sorted(nvd_set),
            "ghsa_value": sorted(ghsa_set),
            "nvd_hosts": nvd_hosts,
            "ghsa_hosts": ghsa_hosts,
            "shared_values": sorted(nvd_set & ghsa_set),
        }

    if (set(nvd_hosts) & set(ghsa_hosts)) or (nvd_set & ghsa_set):
        return {
            "status": "representation_discrepancy",
            "note": "reference coverage differs but points to overlapping evidence sources",
            "nvd_value": sorted(nvd_set),
            "ghsa_value": sorted(ghsa_set),
            "nvd_hosts": nvd_hosts,
            "ghsa_hosts": ghsa_hosts,
            "shared_values": sorted(nvd_set & ghsa_set),
        }

    return {
        "status": "factual_conflict",
        "note": "reference sets are disjoint with no overlapping hosts",
        "nvd_value": sorted(nvd_set),
        "ghsa_value": sorted(ghsa_set),
        "nvd_hosts": nvd_hosts,
        "ghsa_hosts": ghsa_hosts,
    }


def compare_affected_versions(nvd: dict, ghsa: dict) -> dict:
    nvd_spans = normalize_affected_spans(nvd.get("affected") or [])
    ghsa_spans = normalize_affected_spans(ghsa.get("affected") or [])
    missing = compare_missing(nvd_spans, ghsa_spans)
    if missing:
        return {
            **missing,
            "nvd_value": nvd_spans,
            "ghsa_value": ghsa_spans,
        }

    nvd_serialized = {json.dumps(item, sort_keys=True) for item in nvd_spans}
    ghsa_serialized = {json.dumps(item, sort_keys=True) for item in ghsa_spans}
    if nvd_serialized == ghsa_serialized:
        return {
            "status": "equivalent",
            "note": "same canonical version-bound spans",
            "nvd_value": nvd_spans,
            "ghsa_value": ghsa_spans,
        }

    nvd_effective = {effective_affected_span(item) for item in nvd_spans}
    ghsa_effective = {effective_affected_span(item) for item in ghsa_spans}
    if nvd_effective == ghsa_effective:
        return {
            "status": "representation_discrepancy",
            "note": "same effective version bounds after collapsing equivalent upper/lower markers",
            "nvd_value": nvd_spans,
            "ghsa_value": ghsa_spans,
        }

    if nvd_effective.issubset(ghsa_effective) or ghsa_effective.issubset(nvd_effective):
        return {
            "status": "incomplete",
            "note": "one side lists a strict subset of effective version-bound spans",
            "nvd_value": nvd_spans,
            "ghsa_value": ghsa_spans,
        }

    nvd_endpoints = {
        effective_affected_span(item)[2:4]
        for item in nvd_spans
    }
    ghsa_endpoints = {
        effective_affected_span(item)[2:4]
        for item in ghsa_spans
    }
    if nvd_endpoints & ghsa_endpoints:
        return {
            "status": "representation_discrepancy",
            "note": "version-bound spans differ, but share at least one upper-bound endpoint",
            "nvd_value": nvd_spans,
            "ghsa_value": ghsa_spans,
        }

    nvd_end_inc_vals = {
        span["version_end_including"]
        for span in nvd_spans
        if span["version_end_including"]
    }
    nvd_end_exc_vals = {
        span["version_end_excluding"]
        for span in nvd_spans
        if span["version_end_excluding"]
    }
    ghsa_end_exc_vals = {
        span["version_end_excluding"] or span["fixed"]
        for span in ghsa_spans
        if span["version_end_excluding"] or span["fixed"]
    }
    if (
        nvd_end_inc_vals
        and ghsa_end_exc_vals
        and not any(span["version"] for span in nvd_spans)
        and _share_major_minor_prefix(nvd_end_inc_vals, ghsa_end_exc_vals)
    ):
        return {
            "status": "representation_discrepancy",
            "note": "end_including vs end_excluding boundary with shared major.minor prefix",
            "nvd_value": nvd_spans,
            "ghsa_value": ghsa_spans,
        }

    if _all_nvd_points_within_ghsa_ranges(nvd_spans, ghsa_spans):
        return {
            "status": "representation_discrepancy",
            "note": "NVD point versions are covered by GHSA version ranges",
            "nvd_value": nvd_spans,
            "ghsa_value": ghsa_spans,
        }

    if _any_prefix_pair(nvd_end_exc_vals, ghsa_end_exc_vals):
        return {
            "status": "representation_discrepancy",
            "note": "end_excluding version string is a prefix truncation of the other",
            "nvd_value": nvd_spans,
            "ghsa_value": ghsa_spans,
        }

    if any(_is_date_like_version(span.get("version_end_excluding")) for span in nvd_spans):
        return {
            "status": "representation_discrepancy",
            "note": "NVD uses a date string as version_end_excluding",
            "nvd_value": nvd_spans,
            "ghsa_value": ghsa_spans,
        }

    return {
        "status": "factual_conflict",
        "note": "canonical version-bound spans are incompatible",
        "nvd_value": nvd_spans,
        "ghsa_value": ghsa_spans,
    }


def build_unified_view(
    nvd: dict, ghsa: dict, *, reference_normalization_profile: str = "current"
) -> dict:
    return {
        "severity": {
            "nvd": {
                "label": (nvd.get("severity") or {}).get("label"),
                "score": (nvd.get("severity") or {}).get("score"),
                "vector": (nvd.get("severity") or {}).get("vector"),
                "canonical_label": SEVERITY_CANONICAL_MAP.get(
                    ((nvd.get("severity") or {}).get("label") or "").upper()
                ),
            },
            "ghsa": {
                "label": (ghsa.get("severity") or {}).get("label"),
                "score": (ghsa.get("severity") or {}).get("score"),
                "vector": (ghsa.get("severity") or {}).get("vector"),
                "canonical_label": SEVERITY_CANONICAL_MAP.get(
                    ((ghsa.get("severity") or {}).get("label") or "").upper()
                ),
            },
        },
        "published": {
            "nvd": nvd.get("published"),
            "ghsa": ghsa.get("published"),
        },
        "cwe_ids": {
            "nvd": normalize_cwe_ids(nvd.get("cwe_ids") or []),
            "ghsa": normalize_cwe_ids(ghsa.get("cwe_ids") or []),
        },
        "references": {
            "nvd_urls": normalize_reference_urls(
                nvd.get("references") or [],
                profile=reference_normalization_profile,
            ),
            "ghsa_urls": normalize_reference_urls(
                ghsa.get("references") or [],
                profile=reference_normalization_profile,
            ),
            "nvd_hosts": normalize_reference_hosts(nvd.get("references") or []),
            "ghsa_hosts": normalize_reference_hosts(ghsa.get("references") or []),
        },
        "affected_versions": {
            "nvd": normalize_affected_spans(nvd.get("affected") or []),
            "ghsa": normalize_affected_spans(ghsa.get("affected") or []),
        },
        "package_names": {
            "nvd": normalize_package_names(nvd.get("affected") or []),
            "ghsa": normalize_package_names(ghsa.get("affected") or []),
        },
    }


def compare_fields(
    nvd: dict, ghsa: dict, *, reference_normalization_profile: str = "current"
) -> dict:
    return {
        "severity": compare_severity(nvd, ghsa),
        "published": compare_published(nvd, ghsa),
        "cwe_ids": compare_set_field(
            normalize_cwe_ids(nvd.get("cwe_ids") or []),
            normalize_cwe_ids(ghsa.get("cwe_ids") or []),
            overlap_means="representation_discrepancy",
            conflict_note="CWE assignments are disjoint",
        ),
        "references": compare_references(
            nvd,
            ghsa,
            normalization_profile=reference_normalization_profile,
        ),
        "affected_versions": compare_affected_versions(nvd, ghsa),
    }


def iter_matched_pairs(path: Path) -> Iterable[tuple[dict, dict]]:
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            row = json.loads(line)
            ghsa_records = row.get("ghsa") or []
            if len(ghsa_records) != 1:
                continue
            yield row["nvd"], ghsa_records[0]


def write_jsonl(path: Path, rows: Iterable[dict]) -> int:
    count = 0
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=False) + "\n")
            count += 1
    return count


def main() -> int:
    args = parse_args()
    aligned_path = resolve_path(args.aligned_path)
    output_dir = resolve_path(args.output_dir)

    if not aligned_path.exists():
        raise FileNotFoundError(f"Aligned file not found: {aligned_path}")

    pair_output = output_dir / "nvd_ghsa_field_views.jsonl"
    stats_output = output_dir / "field_discrepancy_stats.json"

    field_counters: dict[str, Counter] = defaultdict(Counter)
    processed_pairs = 0

    def rows() -> Iterable[dict]:
        nonlocal processed_pairs
        for nvd_record, ghsa_record in iter_matched_pairs(aligned_path):
            processed_pairs += 1
            unified_view = build_unified_view(
                nvd_record,
                ghsa_record,
                reference_normalization_profile=args.reference_normalization_profile,
            )
            discrepancies = compare_fields(
                nvd_record,
                ghsa_record,
                reference_normalization_profile=args.reference_normalization_profile,
            )
            for field_name, result in discrepancies.items():
                field_counters[field_name][result["status"]] += 1
            output_row = {
                "cve_id": nvd_record.get("cve_id"),
                "nvd_source_id": nvd_record.get("source_id"),
                "ghsa_source_id": ghsa_record.get("source_id"),
                "unified_view": unified_view,
                "field_discrepancies": discrepancies,
            }
            if args.reference_normalization_profile != "current":
                output_row["reference_normalization_profile"] = (
                    args.reference_normalization_profile
                )
            yield output_row

    written = write_jsonl(pair_output, rows())

    stats = {
        "input_aligned_path": str(aligned_path),
        "processed_pairs": processed_pairs,
        "fields": {
            field_name: {
                discrepancy_type: counter.get(discrepancy_type, 0)
                for discrepancy_type in DISCREPANCY_TYPES
            }
            for field_name, counter in sorted(field_counters.items())
        },
    }
    if args.reference_normalization_profile != "current":
        stats["reference_normalization_profile"] = (
            args.reference_normalization_profile
        )
    stats_output.parent.mkdir(parents=True, exist_ok=True)
    stats_output.write_text(
        json.dumps(stats, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    print(f"Unified field views: {pair_output} ({written} pairs)")
    print(f"Field statistics:    {stats_output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
