#!/usr/bin/env python3
"""Build an RQ2 discrepancy-typing annotation seed sample."""

from __future__ import annotations

import argparse
import csv
import json
import random
from collections import Counter, defaultdict
from pathlib import Path
from typing import Iterable


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = "data/processed/bootstrap/discrepancies/nvd_ghsa_field_views.jsonl"
DEFAULT_OUTPUT_DIR = "data/annotations/rq2"
DEFAULT_SEED = 20260524
FIELDS = ("severity", "published", "references", "affected_versions", "cwe_ids")
TARGET_PER_FIELD = 60
STATUSES = (
    "equivalent",
    "representation_discrepancy",
    "incomplete",
    "temporal_discrepancy",
    "factual_conflict",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Sample field instances for RQ2 discrepancy-typing annotation."
    )
    parser.add_argument(
        "--input-path",
        default=DEFAULT_INPUT,
        help="Field view JSONL generated by build_field_discrepancies.py.",
    )
    parser.add_argument(
        "--output-dir",
        default=DEFAULT_OUTPUT_DIR,
        help="Directory for RQ2 annotation seed files.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=DEFAULT_SEED,
        help="Random seed used for reproducible stratified sampling.",
    )
    parser.add_argument(
        "--target-per-field",
        type=int,
        default=TARGET_PER_FIELD,
        help="Number of field instances to sample for each field.",
    )
    return parser.parse_args()


def resolve_path(value: str) -> Path:
    path = Path(value)
    if path.is_absolute():
        return path
    return (PROJECT_ROOT / path).resolve()


def iter_jsonl(path: Path) -> Iterable[dict]:
    with path.open(encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            if not line.strip():
                continue
            row = json.loads(line)
            row["_line_number"] = line_number
            yield row


def json_cell(value) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True)


def compact_json(value, max_chars: int = 420) -> str:
    text = json_cell(value)
    if len(text) <= max_chars:
        return text
    return text[: max_chars - 3] + "..."


def allocate_targets(candidate_counts: dict[str, int], target: int) -> dict[str, int]:
    active = [status for status in STATUSES if candidate_counts.get(status, 0) > 0]
    if not active:
        return {}
    allocation = {status: 0 for status in active}
    remaining = target

    while remaining > 0:
        expandable = [
            status
            for status in active
            if allocation[status] < candidate_counts.get(status, 0)
        ]
        if not expandable:
            break
        per_status = max(1, remaining // len(expandable))
        progressed = False
        for status in expandable:
            capacity = candidate_counts[status] - allocation[status]
            take = min(per_status, capacity, remaining)
            if take <= 0:
                continue
            allocation[status] += take
            remaining -= take
            progressed = True
            if remaining == 0:
                break
        if not progressed:
            break
    return allocation


def build_annotation_row(row: dict, field: str, sample_index: int) -> dict:
    discrepancy = row["field_discrepancies"][field]
    unified_view = row["unified_view"]
    sample_id = f"rq2_discrepancy_typing:{sample_index:03d}"
    return {
        "sample_id": sample_id,
        "source_line_number": row["_line_number"],
        "cve_id": row.get("cve_id"),
        "nvd_source_id": row.get("nvd_source_id"),
        "ghsa_source_id": row.get("ghsa_source_id"),
        "field": field,
        "baseline_status": discrepancy.get("status"),
        "baseline_note": discrepancy.get("note"),
        "nvd_value": discrepancy.get("nvd_value"),
        "ghsa_value": discrepancy.get("ghsa_value"),
        "field_context": unified_view.get(field),
        "package_names": unified_view.get("package_names"),
        "reference_context": unified_view.get("references"),
        "annotation": {
            "manual_status": "",
            "manual_rationale": "",
            "is_baseline_correct": "",
            "needs_adjudication": "",
            "evidence_urls": [],
            "annotator_notes": "",
        },
    }


def write_jsonl(path: Path, rows: list[dict]) -> None:
    with path.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=False) + "\n")


def write_csv(path: Path, rows: list[dict]) -> None:
    fieldnames = [
        "sample_id",
        "source_line_number",
        "cve_id",
        "nvd_source_id",
        "ghsa_source_id",
        "field",
        "baseline_status",
        "baseline_note",
        "nvd_value_json",
        "ghsa_value_json",
        "field_context_json",
        "package_names_json",
        "reference_context_json",
        "manual_status",
        "manual_rationale",
        "is_baseline_correct",
        "needs_adjudication",
        "evidence_urls",
        "annotator_notes",
    ]
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            annotation = row["annotation"]
            writer.writerow(
                {
                    "sample_id": row["sample_id"],
                    "source_line_number": row["source_line_number"],
                    "cve_id": row["cve_id"],
                    "nvd_source_id": row["nvd_source_id"],
                    "ghsa_source_id": row["ghsa_source_id"],
                    "field": row["field"],
                    "baseline_status": row["baseline_status"],
                    "baseline_note": row["baseline_note"],
                    "nvd_value_json": compact_json(row["nvd_value"]),
                    "ghsa_value_json": compact_json(row["ghsa_value"]),
                    "field_context_json": compact_json(row["field_context"]),
                    "package_names_json": compact_json(row["package_names"]),
                    "reference_context_json": compact_json(row["reference_context"]),
                    "manual_status": annotation["manual_status"],
                    "manual_rationale": annotation["manual_rationale"],
                    "is_baseline_correct": annotation["is_baseline_correct"],
                    "needs_adjudication": annotation["needs_adjudication"],
                    "evidence_urls": "",
                    "annotator_notes": annotation["annotator_notes"],
                }
            )


def write_readme(path: Path, manifest: dict) -> None:
    lines = [
        "# RQ2 Discrepancy-Typing Annotation Seed",
        "",
        "This directory contains a stratified seed sample for building the RQ2 human discrepancy-typing gold set.",
        "",
        "The files are annotation templates, not completed gold labels. Baseline labels are deterministic outputs to audit.",
        "",
        "## Files",
        "",
        "- `discrepancy_typing_seed.jsonl`: full JSON annotation template.",
        "- `discrepancy_typing_seed.csv`: spreadsheet-friendly annotation template with compact JSON cells.",
        "- `sample_manifest.json`: sampling configuration and strata counts.",
        "",
        "## Annotation Columns",
        "",
        "- `manual_status`: one of equivalent, representation_discrepancy, incomplete, temporal_discrepancy, factual_conflict, uncertain.",
        "- `manual_rationale`: short reason for the manual status.",
        "- `is_baseline_correct`: yes, no, or uncertain.",
        "- `needs_adjudication`: yes only when the manual status is factual_conflict and evidence adjudication is required.",
        "- `evidence_urls`: optional supporting URLs for boundary cases.",
        "- `annotator_notes`: free-form notes.",
        "",
        "## Sampling Summary",
        "",
        f"- Seed: `{manifest['seed']}`",
        f"- Target per field: `{manifest['target_per_field']}`",
        f"- Total sampled instances: `{manifest['sampled_count']}`",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    args = parse_args()
    input_path = resolve_path(args.input_path)
    output_dir = resolve_path(args.output_dir)
    if not input_path.exists():
        raise FileNotFoundError(f"Field view file not found: {input_path}")

    output_dir.mkdir(parents=True, exist_ok=True)
    rows = list(iter_jsonl(input_path))
    rng = random.Random(args.seed)

    by_field_status: dict[str, dict[str, list[dict]]] = {
        field: defaultdict(list) for field in FIELDS
    }
    for row in rows:
        for field in FIELDS:
            discrepancy = row.get("field_discrepancies", {}).get(field)
            if not discrepancy:
                continue
            status = discrepancy.get("status")
            by_field_status[field][status].append(row)

    selected_rows = []
    strata = []
    sample_index = 1
    for field in FIELDS:
        counts = {
            status: len(by_field_status[field].get(status, [])) for status in STATUSES
        }
        targets = allocate_targets(counts, args.target_per_field)
        for status in STATUSES:
            target = targets.get(status, 0)
            candidates = by_field_status[field].get(status, [])
            sampled = rng.sample(candidates, target) if target else []
            for row in sampled:
                selected_rows.append(build_annotation_row(row, field, sample_index))
                sample_index += 1
            strata.append(
                {
                    "field": field,
                    "baseline_status": status,
                    "candidate_count": counts.get(status, 0),
                    "sampled_count": len(sampled),
                }
            )

    jsonl_path = output_dir / "discrepancy_typing_seed.jsonl"
    csv_path = output_dir / "discrepancy_typing_seed.csv"
    manifest_path = output_dir / "sample_manifest.json"
    readme_path = output_dir / "README.md"

    status_counts = Counter(
        (row["field"], row["baseline_status"]) for row in selected_rows
    )
    manifest = {
        "input_path": str(input_path),
        "output_dir": str(output_dir),
        "seed": args.seed,
        "target_per_field": args.target_per_field,
        "sampled_count": len(selected_rows),
        "fields": list(FIELDS),
        "statuses": list(STATUSES),
        "strata": strata,
        "sampled_distribution": [
            {
                "field": field,
                "baseline_status": status,
                "sampled_count": status_counts.get((field, status), 0),
            }
            for field in FIELDS
            for status in STATUSES
            if status_counts.get((field, status), 0)
        ],
        "cautions": [
            "This is an annotation template, not a completed human gold set.",
            "Baseline statuses are deterministic labels to audit, not ground truth.",
            "RQ2 accuracy, macro-F1, precision, and recall require completed manual_status labels.",
        ],
        "jsonl_path": str(jsonl_path),
        "csv_path": str(csv_path),
        "readme_path": str(readme_path),
    }

    write_jsonl(jsonl_path, selected_rows)
    write_csv(csv_path, selected_rows)
    manifest_path.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    write_readme(readme_path, manifest)

    print(f"Wrote {jsonl_path}")
    print(f"Wrote {csv_path}")
    print(f"Wrote {manifest_path}")
    print(f"Wrote {readme_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
